name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '11 1 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true

    strategy:
      matrix:
        compiler:
          - clang
          - gcc
        container:
          - almalinux:8
          - alpine:3.18
          - ubuntu:20.04

    container: ${{ matrix.container }}

    steps:
      - name: Checkout ProFTPD
        uses: actions/checkout@v3
        with:
          repository: proftpd/proftpd
          path: proftpd

      - name: Checkout module source code
        uses: actions/checkout@v3
        with:
          path: proftpd/contrib/mod_sftp_openssh

      - name: Whitespace check
        if: ${{ matrix.container == 'ubuntu:20.04' }}
        run: |
          apt-get update -qq
          apt-get install -y git
          cd proftpd/contrib/mod_sftp_openssh
          if [[ -n $(git diff --check HEAD^) ]]; then
            echo "You must remove whitespace before submitting a pull request"
            echo ""
            git diff --check HEAD^
            exit 1
          fi

      - name: Install Alpine packages
        if: ${{ matrix.container == 'alpine:3.18' }}
        run: |
          apk update
          # for builds
          apk add bash build-base clang compiler-rt gcc make zlib-dev

          # for OpenSSL support
          apk add openssl openssl-dev

          # for debugging
          clang --version
          gcc --version
          openssl version -a

      - name: Install RPM packages
        if: ${{ matrix.container == 'almalinux:8' }}
        run: |
          # Need to add other repos for e.g. libsodium
          yum install -y dnf-plugins-core epel-release yum-utils clang gcc make zlib-devel
          dnf config-manager --enable epel
          dnf config-manager --set-enabled powertools

          # for OpenSSL support
          yum install -y openssl openssl-devel

          # for debugging
          clang --version
          gcc --version
          openssl version -a

      - name: Install Ubuntu packages
        if: ${{ matrix.container == 'ubuntu:20.04' }}
        run: |
          apt-get update -qq
          # for builds
          apt-get install -y clang gcc make

          # for OpenSSL support
          apt-get install -y libssl-dev

          # for HTML validation
          apt-get install -y tidy
          # for debugging
          clang --version
          gcc --version
          openssl version -a

      - name: Build as static module
        env:
          CC: ${{ matrix.compiler }}
        run: |
          cd proftpd
          ./configure LIBS="-lm -lrt -pthread" --with-modules=mod_sftp:mod_sftp_openssh
          make

      - name: Install as static modules
        run: |
          cd proftpd
          make install

      - name: Build as shared modules
        env:
          CC: ${{ matrix.compiler }}
        run: |
          cd proftpd
          make clean
          ./configure LIBS="-lm -lrt -pthread" --enable-devel --enable-dso --with-shared=mod_sftp:mod_sftp_openssh
          make

      - name: Install as shared modules
        run: |
          cd proftpd
          make install

      - name: Check HTML docs
        if: ${{ matrix.container == 'ubuntu:20.04' }}
        run: |
          cd proftpd/contrib/mod_sftp_openssh
          for f in $(/bin/ls *.html); do echo "Processing $f"; tidy -errors -omit -q $f; done || exit 0
