name: Regression Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.html'
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.codeql.yml'
      - '**/*.html'
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEBIAN_FRONTEND: noninteractive
      TZ: America/Los_Angeles

    strategy:
      matrix:
        compiler:
          - gcc
        container:
          - ubuntu:22.04

    container: ${{ matrix.container }}

    steps:
      - name: Checkout ProFTPD
        uses: actions/checkout@v3
        with:
          repository: proftpd/proftpd
          path: proftpd

      - name: Checkout mod_sftp_openssh source code
        uses: actions/checkout@v3
        with:
          repository: Castaglia/proftpd-mod_sftp_openssh
          path: proftpd/contrib/mod_sftp_openssh

      - name: Install Ubuntu packages
        run: |
          apt-get update -qq
          # for builds
          apt-get install -y gcc git make tzdata

          # for OpenSSL support
          apt-get install -y libssl-dev

          # for Sodium support
          apt-get install -y --force-yes libsodium-dev

          # for integration/regression tests
          apt-get install -y \
            libauthen-oath-perl \
            libcompress-raw-zlib-perl \
            libdata-dumper-simple-perl \
            libdatetime-perl \
            libfile-copy-recursive-perl \
            libfile-path-tiny-perl \
            libfile-spec-native-perl \
            libmime-base32-perl \
            libnet-address-ip-local-perl \
            libnet-inet6glue-perl \
            libnet-ssh2-perl \
            libnet-ssleay-perl \
            libnet-telnet-perl \
            libposix-2008-perl \
            libtest-unit-perl \
            libtime-hr-perl \
            libwww-perl

          # for debugging
          gcc --version
          openssl version -a

      - name: Install with static modules
        # NOTE: Docker does not have good IPv6 support, hence we disable it.
        run: |
          cd proftpd
          ./configure --enable-ctrls --disable-ipv6 --with-modules=mod_sftp:mod_sftp_openssh
          make
          ./proftpd -V
          make install

      - name: Run integration tests
        env:
          PROFTPD_TEST_BIN: /usr/local/sbin/proftpd
          PROFTPD_TEST_CI: github
          PROFTPD_TEST_DIR: ${{ github.workspace }}/proftpd/tests
        run: |
          cd proftpd/contrib/mod_sftp_openssh
          perl tests.pl
